stages:
  make_dataset:
    cmd: python ./src/data/make_dataset.py
    deps:
    - ./src/data/make_dataset.py
  build_features:
    cmd: python ./src/features/build_features.py
    deps:
    - ./src/features/build_features.py
  train_model:
    cmd: python ./src/models/train_model.py
    deps:
    - ./src/models/train_model.py
    